package com.freelance.Batchreports.constants;

public class FieldConstants {
    public static final String PLANT_NAME = "plantName";
    public static final String BATCH_DATE = "batchDate";
    public static final String BATCH_START_TIME = "batchStartTime";
    public static final String BATCH_END_TIME = "batchEndTime";
    public static final String BATCH_NO = "batchNo";
    public static final String CUSTOMER = "customer";
    public static final String SITE = "site";
    public static final String RECIPE_CODE = "recipeCode";
    public static final String RECIPE_NAME = "recipeName";
    public static final String TRUCK_NUMBER = "truckNumber";
    public static final String TRUCK_DRIVER = "truckDriver";
    public static final String ORDER_NO = "orderNo";
    public static final String BATCHER_NAME = "batcherName";
    public static final String PLANT_SERIAL_NO = "planSerialNo";
    public static final String ORDERED_QUANTITY = "orderedQuantity";
    public static final String PRODUCTION_QUANTITY = "prodQuantity";
    public static final String MANUAL_QUANTITY = "manualQuantity";
    public static final String MIXER_QUANTITY = "mixerQuantity";
    public static final String WithThisLoad = "withthisload";
    public static final String BATCH_SIZE = "batchSize";

    public static final String AGG1_NAME = "agg1Name";
    public static final String AGG2_NAME = "agg2Name";
    public static final String AGG3_NAME = "agg3Name";
    public static final String AGG4_NAME = "agg4Name";
    public static final String AGG5_NAME = "agg5Name";
    public static final String CEMENT1_NAME = "cement1Name";
    public static final String CEMENT2_NAME = "cement2Name";
    public static final String FILL_NAME = "fillName";
    public static final String WATER1_NAME = "water1Name";
    public static final String WATER2_NAME = "water2Name";
    public static final String SILICA_NAME = "silicaName";
    public static final String ADMIX1_NAME = "admix1Name";
    public static final String ADMIX2_NAME = "admix2Name";

    public static final String GATE1_TARGET = "gate1Target";
    public static final String GATE2_TARGET = "gate2Target";
    public static final String GATE3_TARGET = "gate3Target";
    public static final String GATE4_TARGET = "gate4Target";
    public static final String GATE5_TARGET = "gate5Target";
    public static final String CEMENT1_TARGET = "cement1Target";
    public static final String CEMENT2_TARGET = "cement2Target";
    public static final String FILLER_TARGET = "fillerTarget";
    public static final String WATER1_TARGET = "water1Target";
    public static final String WATER2_TARGET = "water2Target";
    public static final String SILICA_TARGET = "silicaTarget";
    public static final String ADM1_TARGET1 = "adm1Target1";
    public static final String ADM1_TARGET2 = "adm1Target2";

    public static final String GATE1_ACTUAL_TOTAL = "gate1ActualTotal";
    public static final String GATE2_ACTUAL_TOTAL = "gate2ActualTotal";
    public static final String GATE3_ACTUAL_TOTAL = "gate3ActualTotal";
    public static final String GATE4_ACTUAL_TOTAL = "gate4ActualTotal";
    public static final String GATE5_ACTUAL_TOTAL = "gate5ActualTotal";
    public static final String CEMENT1_ACTUAL_TOTAL = "cement1ActualTotal";
    public static final String CEMENT2_ACTUAL_TOTAL = "cement2ActualTotal";
    public static final String FILLER1_ACTUAL_TOTAL = "filler1ActualTotal";
    public static final String WATER1_ACTUAL_TOTAL = "water1ActualTotal";
    public static final String WATER2_ACTUAL_TOTAL = "water2ActualTotal";
    public static final String SILICA_ACTUAL_TOTAL = "silicaActualTotal";
    public static final String ADM1_ACTUAL_TOTAL = "adm1Actual1Total";
    public static final String ADM2_ACTUAL_TOTAL = "adm2Actual1Total";

    public static final String AGG1_NAMEX = "agg1NameNX";
    public static final String AGG2_NAMEX = "agg2NameNX";
    public static final String AGG3_NAMEX = "agg3NameNX";
    public static final String AGG4_NAMEX = "agg4NameNX";
    public static final String AGG5_NAMEX = "agg5NameNX";
    public static final String CEMENT1_NAMEX = "cement1NameNX";
    public static final String CEMENT2_NAMEX = "cement2NameNX";
    public static final String FILL_NAMEX = "fillNameNX";
    public static final String WATER1NAMEX = "water1NameNX";
    public static final String WATER2NAMEX = "water2NameNX";
    public static final String SILICANAMEX = "silicaNameNX";
    public static final String ADMX1NAMEX = "admix1NameNX";
    public static final String ADMX2NAMEX = "admix2NameNX";
}
